movieapp/urls.py
from django.urls import path
from . import views
app_name="movieapp"

urlpatterns = [
    path("",views.index,name="home"),
    path("movies/<int:movie_id>/",views.detail,name="details"),
    path("add/",views.add,name="added"),
    path("update/<int:id>/",views.update,name="edit"),
    path("delete/<int:id>",views.delete,name="remove")
]

movieproject/urls.py
from django.contrib import admin
from django.urls import include, path

from movieproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("movieapp.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.

class Movies(models.Model):
    name=models.CharField(max_length=200)
    description=models.CharField(max_length=200)
    year=models.CharField(max_length=200)
    genre=models.CharField(max_length=200)
    image=models.ImageField(upload_to="gallery")


    def __str__(self):
        return self.name

movieapp/forms.py
from .models import Movies
from django import forms


class MovieForm(forms.ModelForm):
    class Meta:
        model=Movies
        fields=["name","description","year","genre","image"]
    

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from . models import Movies
from .forms import MovieForm

# Create your views here.

def index(request):
    movie_list=Movies.objects.all()
    return render(request,"index.html",{"context":movie_list})

def detail(request,movie_id):
    movie=Movies.objects.get(id=movie_id)
    return render(request,"detail.html",{"movie_detail":movie})

def add(request):
    if request.method == "POST":
        name=request.POST.get("name",)
        desc=request.POST.get("desc",)
        year=request.POST.get("year",)
        genre=request.POST.get("genre",)
        img=request.FILES["img"]
        movie=Movies(name=name,description=desc,year=year,genre=genre,image=img)
        movie.save()
    return render(request,"add.html")
    

def update(request,id):
    movie=Movies.objects.get(id=id)
    form=MovieForm(request.POST or None , request.FILES ,instance=movie)
    if form.is_valid():
        form.save()
        return redirect("/")
    return render(request,"edit.html",{"form":form,"movie":movie})


def delete(request,id):
    if request.method== "POST":
        movie=Movies.objects.get(id=id)
        movie.delete()
        return redirect("/")
    return render(request,"delete.html")

templates/add.html
{% extends 'base.html' %}
{% block body %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="text" name="name" placeholder="Enter the movie name" class="form-control-lg"><br><br>
    <input type="text" name="desc" placeholder="Enter the movie description" class="form-control-lg"><br><br>
    <input type="text" name="year" placeholder="Enter the movie year" class="form-control-lg"><br><br>
    <input type="text" name="genre" placeholder="Enter the movie genre" class="form-control-lg"><br><br>
    <input type="file" name="img" class="form-control-lg"><br><br>
    <input type="submit" class="btn btn-dark">

</form>


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
  <nav class="navbar bg-body-tertiary bg-dark">
    <div class="container-fluid" style="height: 50px;">
      <a class="navbar-brand" href="#">

        <h4 style="color: white;">Online movie hub</h4>
      </a>
    </div>
    <div>
      <div class="mx-4">
        <a href="{% url 'movieapp:added'%}" type="button" class="btn btn-light rounded-pill fw-bolder mb-1">ADD</a>
    </div>
  </div>
  </nav>
  {% block body %}

  {% endblock %}


</body>

</html>

templates/delete.html
<form action="" method="post">
    {% csrf_token %}
    <h5>Are you sure yiu want to delete this item</h5>
    <input type="submit" value="YES">
</form>

templates/detail.html
{% extends 'base.html'%}
{% block body %}

<div class="container">
    <div class="row">
        <div class="card mb-3 centre" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{movie_detail.image.url}}" class="img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{movie_detail.name}}</h5>
                        <p class="card-text">{{movie_detail.description}}</p>
                        <p class="card-text">Year: {{movie_detail.year}}</p>
                        <p class="card-text">Genre: {{movie_detail.genre}}</p>
                        <a type="button" class="btn btn-outline-success"
                            href="{% url 'movieapp:edit' movie_detail.id %}">Edit</a><br>
                        <a type="button" class="btn btn-outline-danger mt-4"
                            href="{% url 'movieapp:remove' movie_detail.id %}">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}
</body>

</html>

templates/edit.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" value="submit">
</form>

templates/index.html
{% extends 'base.html'%}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in context %}
        <div class="col-lg-3 mt-5">
            <div class="card" style="width: 200px;">
                <img src="{{i.image.url}}" class="card-img-top" alt="..."  height="200px">
                <div class="card-body">
                  <h5 class="card-title">{{i.name}}</h5>
                  <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
                  <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">View more</a>
                </div>
              </div>
        </div>
        {% endfor %}
        
    </div>
</div>

{% endblock %}